### ISSUE TITLE
Resolve all Eclipse specific dependencies in EAVP

### ISSUE THREAD

**Issue by anarak** [eclipse/eavp#148]
This ticket will contain all the issues related to Eclipse workbench dependencies. I think listing them all here as a list will help tracking them individually.

- [ ] EAVP service can not be consumed #147 
- [ ] Null pointer exception when creating a new plot with CSVVizService #149
- [ ] When creating a plot with CSVVizService URI is not validated properly #150
- [ ] ParaView and VisIt viz services depend on specific connection services #151
- [ ] No configured connection to host 'localhost' #152
- [ ] Refactoring XYZSeriesStyle class #153

**Comment by anarak** [comment]
Jay insisted to put this pic here for "documentation" purposes
![20170511_133820](https://cloud.githubusercontent.com/assets/25353166/25971286/b1627034-3669-11e7-9946-4f295af4c648.jpg)

**Comment by amccaskey** [comment]
@anarak 

This is a great picture to see. It really gives me a better understanding on the EAVP architecture. And I'm sure it was a big help for you to go through this exercise since you are so new to the project. Just seeing the total UML diagram of the architecture like this will really help us in our refactoring to enable EAVP on the web via Vaadin. 

And this really is a great habit for us to get into - putting our whiteboard drawings up on an Issue Tracker. Thanks for posting this.

**Comment by jayjaybillings** [comment]
We already put quite a few whiteboard pictures up on here... most of them are in the ICE tracker though.

Thanks @anarak. Did you get pictures of the board in the main room as well?

**Comment by anarak** [comment]
@amccaskey I feel I'm pioneering some new practices in this team. This is by no means an UML diagram, just  a casual drawing. @jayjaybillings I couldn't find any whiteboard pictures in ICE github issues/bug reports.

**Comment by jayjaybillings** [comment]
Our practices are a discussion for another time, but this is a good UML Class diagram. Very good work.

This accurately captures the separation of SWT versus native EAVP code in the project.

**Comment by anarak** [comment]
@jayjaybillings yes, I got those pictures, do you want me to post here the pictures from the main room as well?

**Comment by jayjaybillings** [comment]
Yes, please. I'll chat with you shortly about the report I asked for though, so no need to describe the pictures.

**Comment by anarak** [comment]
Uploading pictures from my phone is taking some time. Will upload the rest of the pictures tomorrow.

**Comment by jayjaybillings** [comment]
Okay, thanks.

**Comment by anarak** [comment]
![20170511_110857](https://cloud.githubusercontent.com/assets/25353166/25998735/626b2fa2-36f0-11e7-9b13-e88bb6f0a90c.jpg)
![20170511_110847](https://cloud.githubusercontent.com/assets/25353166/25998746/6a5ab552-36f0-11e7-8489-207db3d86a73.jpg)

**Comment by jayjaybillings** [comment]
@SmithRWORNL finished this in his refactor branch I believe. If not, let's reopen as a more specific ticket.
